apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::364119579355:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SKMOZKW3YW8D
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::364119579355:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-26T22:32:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1279"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 596e13e5-26ba-4632-b5bf-3ea1a9c1825d
